// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ConfettiBuild
{
    internal sealed partial class Vsix
    {
        public const string Id = "ConfettiBuild.bd481d3b-bf4d-4847-88aa-b7849e23a1f8";
        public const string Name = "ConfettiBuild";
        public const string Description = @"This extension plays a nice confetti animation when the solution or project builds";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Adolfo Marinucci";
        public const string Tags = "";
    }
}
